version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: root_pswrd
      MARIADB_DATABASE: app
      MARIADB_USER: symfony
      MARIADB_PASSWORD: ChangeMe
    volumes:
       - ./docker/db/data:/var/lib/mysql:rw
    ports:
      - '3306:3306'
